sudo: false
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
dist: trusty
script:
  - mvn cobertura:cobertura
  - travis_wait 360 mvn clean test -U
after_success: - bash <(curl -s https://codecov.io/bash)
before_deploy:
- gpg --import .travis.key.gpg
- mvn versions:set -DnewVersion=${TRAVIS_TAG}
deploy:
  provider: script
  skip_cleanup: true
  script: mvn clean deploy -P release --settings .travis.settings.xml
  on:
    tags: true
env:
  global:
  - secure: pGTwV9B/lzFjOlCUWOc+bLkQO8/gMYywTt51dpQi5nodKb9ISZWFdBLxCEVdx3hctjAOS1X4AM/Chbry8jf1wRQ26g21dZ6oHr93wdenp08ME3gYVkl5bAV6x2toZiaiAbSATk/iFt2Cz1BAUeDzrS867ZYDMTEmIQIZpPRAbQPxLTQ0dfALCd9rjN944cXE5nyNiPzTfwkmeegOTC6/x0ZXxsmY+4k6mH5RfDP4ePP6MERk88TiCRvBGt+BHn/i5dTx5pUroJtECpcshnuKVroyf1YAA+y+wuXjk4GWKLHmby89JjCQ+nzL7BJwfqqNscagDTLTxvr4y2wlq6ohS6R+hB2w9QzGfocXw9K/ihTVWM9LFLPlmQVdP49u7QeRf+2rGxP5vvYAzUYEYcaZEk05eqXGw2dKS0AD1lBGOoq44yC/tG/wRKdPJAdKcF+uDAD4UTyNzeCYpDuaTBIh9l8CECj+DN5XeqRZOjpbUiE/Gq6mNPKZr84a1m/66g+CayTojEY7HgGNIQEKyyKt01I8ZQersbHlwEsZMBAiVPZcd7pnrfkytgc3lGaGUJyAx8O9nSFaU/RWeoH4ablUSIcTzWtTKa9q990y+ciXEiZr5CnpfVMujFDPegEGYc+z1easyBTTD62RoQfihHv7YQz9qEyWQEwNA/pLGPwkFV0=
  - secure: hy5wmSjaqI/YTzVY4CB1Ry6FF173oSfxE9rjHtmJXx57SlBgeDSoV5Evc1CuQwtH4MoaHEqiWpzC+p1tLP6wtVvbXYhZtB/jJH6W7Pp2t52K1S8KphGL5IZncy9BHt83ZI1+dv4ItDt4FcQUx+bmS3DDoeRqfa+xefLH1Zq+vurecTqDJDGEnWh9ii7GSdrR/HqB07npxub6LG9WMX0urzdbl2YjyLHiXHEXEMa6CsVwtj+jZQBH+jnGk5j//Gx9Y2rzm+LLOKgcreUv6QKB58TXqtRFsWiP1Eekc6XvoJ9/RB4kVzpSJ5jWm8WPjbWRt23JyfcX8AM+eCZfeC2qbhBhMd9E6fzrSQPqQ3xI4Jiigz+E9LT/bBQuScfLeg3hnpir4boEIgeBBfH69shLXOZmszBVWhjzuTzxg8uWuxAlOlkIlX49X61uS8Z9TBxAObEp53ORiYVvOiFd0+wof5cVCRp+wTDX+ym+v+5cpL+7ssXp3CvLd+3A4iXLOJZU/AxQ2UyPzNBbJQ5320wAb7HPmewhaurKB251OjUdSG2bYhE1kh9kl3w3lXkGJh/xy3mefjjjeyDZyoq4gF3ysn5LSwzpe4ZC44FvthNYFtMLl5cBAM/fvmGK6l2p6B7ZsX60ZZCN21ZgD388u2z12uU3OqClbIUiK9dLkVHypEU=
  - secure: AEB3n/9ksSCgYn+anyMIYPD2vKjKC/B6a5gacRwPy3W5fjqhguHFOalZ3QngHf3pCgVqMSvgq8GnxNcCaQVWllMm/jru/zaYNxIGXfaIg+IgBIhd45rvnhyulsm5jpzVxWdECvQw0uuxj8cuO+fmk5zhR+rPTrAmohq09MhWNeJuXE7uaRvh9BiYnt9CJlFW8IojCVGTIOLy2bbn+6iIgZJ/l8D0yCJIgZ2USCXsbNMyvOiBlkBvTY7fT87lnFTjzvBjLenlb8HL5u5igpYYgWq/AcBlS8Uszq3KHERhWWAQVXonfx30ZMpOEjjFdH8Ik8ahPnb1JM1D2zZ+7EGEKO69UsVWYs/ZeYB8jP+mCgS1+/ud6r4HkAHtUJhqhT/xTKI/rejt8IXD/W7WfejwGtcP0g67Ho0W7s3RELbuwoVaRY6fICwx42rxSDqdFgs8mTzH4dyE6XljXBqdFZn8GMyM9Qsd01KEBmxaWhMfrYBi52G/9I+Xx9V5ntRCh2BrzEZ+5F6XQXepSv8CPOuRAo4g4yk5WbCCDM2WGHcRZ8fde0UOKxNfjdnZ3uYnACqBqtgbPZic4laU90JtZcPt3yUb+ErmIzP12U0MK2ST2MIeqFnkkZXSYNt/cR7kkQ8xq1KDVPIM8ltz8e8Disgr3rb9IosrtOyGQ66Tnh8zdkQ=
